[project]
name = "dspt2025-ml"
version = "0.1.0"
description = "Ejemplo de un proyecto usando UV"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.8.1",
    "diffusers>=0.34.0",
    "huggingface-hub>=0.33.4",
    "ipykernel>=6.29.5",
    "langchain-openai>=0.3.28",
    "matplotlib>=3.10.3",
    "nbformat>5",
    "openai>=1.95.1",
    "pydot>=4.0.1",
    "python-dotenv>=1.1.1",
    "sdv>=1.24.0",
    "tensorflow>=2.19.0",
    "tf-keras>=2.19.0",
    "transformers>=4.53.2",
]
